---
extends: default

ignore:
  - tests/

rules:
  braces: {min-spaces-inside: 0, max-spaces-inside: 1}
  brackets: {min-spaces-inside: 0, max-spaces-inside: 1}
  comments: {min-spaces-from-content: 1}
  document-start: disable
  indentation:
    indent-sequences: consistent
  # Ignore the line length rule in this repo. 120 chars should be enough for the
  # stuff we control, but we can't control the test outputs, which are currently
  # saved in YAML files.
  line-length:
    disable
    # We could downgrade the line length error to a warning, but for now it clutters the output too much.
    # max: 120
    # level: warning
  truthy:
    allowed-values: ['true', 'false', 'on']
