/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.code.gson:gson:2.8.8")
    compileClasspath("com.google.code.gson:gson:2.8.8")
    runtimeClasspath("com.google.code.gson:gson:2.8.8")
    testCompileClasspath("com.google.code.gson:gson:2.8.8")
    testRuntimeClasspath("com.google.code.gson:gson:2.8.8")
}

dependencyLocking {
    lockAllConfigurations()
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
