/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "demo"
include("app")

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention").version("0.10.0")
}