# Runs a single ecosystem without cache and does not fill the cache.
name: Dry run

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      git-ref:
        description: git ref
        required: true
        default: main
      test:
        description: smoke test to run (e.g. go, go-close-pr, etc)
        required: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dry_run:
    runs-on: ubuntu-latest
    name: Dry run ${{ inputs.test }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git-ref }}

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: stable

      - name: Install Dependabot CLI
        run: go install github.com/dependabot/cli/cmd/dependabot@latest

      # No download first to get a clean cache.

      - name: Smoke ${{ inputs.package_manager }}
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dependabot test -f=tests/smoke-${{ inputs.test }}.yaml --cache=cache

        # No upload
